// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/blog/[id].tsx";
import * as $4 from "./routes/blog/index.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/p/[id].tsx";
import * as $7 from "./routes/proyectos/[id].tsx";
import * as $8 from "./routes/proyectos/index.tsx";
import * as $$0 from "./islands/Button.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/drop-down-menu.tsx";
import * as $$3 from "./islands/toggle-button.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/blog/[id].tsx": $3,
    "./routes/blog/index.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/p/[id].tsx": $6,
    "./routes/proyectos/[id].tsx": $7,
    "./routes/proyectos/index.tsx": $8,
  },
  islands: {
    "./islands/Button.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/drop-down-menu.tsx": $$2,
    "./islands/toggle-button.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
